fishcollector/urls.py
from django.contrib import admin
 # Add the include function to the import
from django.urls import path, include
	
urlpatterns = [
     path('admin/', admin.site.urls),
     # '' represents the "starts with" path
     path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views
	
urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('fishes/', views.fishes_index, name='index'),
  path('fishes/<int:fish_id>/', views.fishes_detail, name='detail'),
  path('fishes/create/', views.FishCreate.as_view(), name='fishes_create'),
  path('fishes/<int:pk>/update', views.FishUpdate.as_view(), name="fishes_update"),
  path('fishes/<int:pk>/delete', views.FishDelete.as_view(), name="fishes_delete"),
  path('fishes/<int:fish_id>/add_feeding/', views.add_feeding, name='add_feeding'),
  path('toys/', views.ToyList.as_view(), name='toys_index'),
  path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
  path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
  path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
  path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

# Create your models here.
class Toy(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('toys_detail', kwargs={'pk': self.id})

class Fish(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)


    def __str__(self):
        return f'{self.name} ({self.id})'

    def get_absolute_url(self):
        return reverse('detail', kwargs={'fish_id': self.id})

class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1,
        choices = MEALS,
        default= MEALS[0][0]
    )
    fish = models.ForeignKey(
        Fish,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.get_meal_display()} on {self.date}'

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Fish, Toy
from .forms import FeedingForm


# Create your views here.

# Define the home view
def home(request):
  # Include an .html file extension - unlike when rendering EJS templates
  return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def fishes_index(request):
    fishes = Fish.objects.all()
    return render(request, 'fishes/index.html', {
        'fishes': fishes

})

def fishes_detail(request, fish_id):
    fish = Fish.objects.get(id=fish_id)
    feeding_form = FeedingForm()
    return render(request, 'fishes/detail.html', {
        'fish': fish, 'feeding_form': feeding_form
    })

class FishCreate(CreateView):
    model = Fish
    fields = '__all__'

class FishUpdate(UpdateView):
    model = Fish
    fields = ['breed', 'description', 'age']

class FishDelete(DeleteView):
    model = Fish
    success_url = '/fishes'

def add_feeding(request, fish_id):
    form = FeedingForm(request.POST)

    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.fish_id = fish_id
        new_feeding.save()
    return redirect('detail', fish_id=fish_id)

class ToyList(ListView):
  model = Toy

class ToyDetail(DetailView):
  model = Toy

class ToyCreate(CreateView):
  model = Toy
  fields = '__all__'

class ToyUpdate(UpdateView):
  model = Toy
  fields = ['name', 'color']

class ToyDelete(DeleteView):
  model = Toy
  success_url = '/toys'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Fish Collector</h1>
<hr>
<p>Hire the Fish Collector!</p>


{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Fish Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Fish Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
          <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
          <li><a href="{% url 'fishes_create' %}">Add A Fish</a></li>
          <li><a href="{% url 'index' %}">View My Fish</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Fish Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/fishes/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Fish</h1> Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ fish.name }}</span>
        <p>Breed: {{ fish.breed }}</p>
        <p>Description: {{ fish.description|linebreaks }}</p>
        {% if fish.age > 0 %}
          <p>Age: {{ fish.age }}</p>
        {% else %}
          <p>Age: Guppy</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'fishes_update' fish.id %}">Edit</a>
        <a href="{% url 'fishes_delete' fish.id %}">Delete</a>
      </div>
    </div>
  </div>
  <!-- New Markup Below -->
  <div class="col s6">
    <form action="{% url 'add_feeding' fish.id %}" method="POST">
      {% csrf_token %}
      {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in fish.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- New Markup Above -->
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/fishes/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Fish List</h1>

{% for fish in fishes %}
<a href="{% url 'detail' fish.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ fish.name }}</span>
      <p>Breed: {{ fish.breed }}</p>
      <p>Description: {{ fish.description|linebreaks }}</p>
      {% if fish.age > 0 %}
        <p>Age: {{ fish.age }}</p>
      {% else %}
        <p>Age: Guppy</p>
      {% endif %}
    </div>
  </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Home</h1>

{% endblock %}

main_app/templates/main_app/fish_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Fish</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' fish.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/fish_form.html
{% extends 'base.html' %}

{% block content %}

  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Fish</h1>
  {% endif %}

  
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Toy</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>

{% for toy in toy_list %}
  <a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}